project:
  type: website

website:
  title: "Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data.qmd
        text: Historic Exploratory Data Analysis
      - href: microclimate.qmd
        text: Microclimate Clustering
      - href: future.qmd
        text: Future Modeling and Scenarios

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true



